name: drails_commons
version: 0.0.2
author: Luis Vargas <luisvargastijerino@gmail.com>
description: Package used for drails_server and can be shared for other libraries, includent client side libraries.
homepage: https://github.com/luisvt/Drails/tree/master/drails_commons
environment:
  sdk: '>=1.6.0'
dependencies:
  logging: '>=0.9.2 <0.10.0'
